version: '3.1'

services:

  bookmedik:
    container_name: servidor-bookmedik
    image: alvarovaca/nginx:v1
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: user_bookmedik
      MYSQL_PASSWORD: pass_bookmedik
    ports:
      - 8081:80
    volumes:
      - /home/alvaro/GitHub/practicadocker/Tarea 3/build1/bookmedik:/bookmedik

  phpfpm:
    container_name: phpfpm-bookmedik
    image: alvarovaca/phpfpm:v1
    restart: always
    volumes:
      - /home/alvaro/GitHub/practicadocker/Tarea 3/build1/bookmedik:/bookmedik

  dbbookmedik:
    container_name: mariadb-bookmedik
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: user_bookmedik
      MYSQL_PASSWORD: pass_bookmedik
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - /home/alvaro/datadir:/var/lib/mysql
